apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "fullname" . }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  {{- range .Values.containers }}{{- range .routes }}
    - port:
        number: {{ .port }}
        name: {{ .name }}
        protocol: HTTP # {{ .protocol }}
      hosts:
        - {{ .hostname }}
  {{- end }}{{- end }}
      
