{{- if .Values.ingress.enabled }}
{{- $fullName := include "fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
    - hosts:
      {{- range .Values.containers }}{{- range .routes }}{{- if .tls }}
        - {{ .hostname }}
      {{- end }}{{- end }}{{- end }}
      secretName: {{ template "fullname" . }}-tls
  rules:
  {{- range .Values.containers }}{{- range .routes }}{{- if .hostname }}
    - host: {{ .hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-istio-ingressgateway
              servicePort: {{ .port }}
  {{- end }}{{- end }}{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-istio-ingressgateway
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ExternalName
  externalName: istio-ingressgateway.istio-system.svc.cluster.local
{{- end }}
