{{ $fullname := include "fullname" . }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}
spec:
  hosts:
  {{- if .Values.ingress.enabled }}{{- range .Values.containers }}{{- range .routes }}{{- if .hostname }}
    - {{ .hostname }}
  {{- end }}{{- end }}{{- end }}{{- end }}
    - {{ template "fullname" . }}
  gateways:
    - {{ template "fullname" . }}
  http:
    {{- range .Values.containers }}{{- range .routes }}
    - route:
        - destination:
            host: {{ $fullname }}
            port:
              number: {{ .port }}
    {{- end }}{{- end }}
