service:
  name: string
  secrets: secrets
  container: repeated container
  ingress: ingress
  rawValues: repeated rawValues
  configPath: string
  secretsPath: string
  mounts: repeated mount

context: mapped service
